[package]
name = "advent-code-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.164"
serde_yaml = "0.9.21"
tera = "1.19.0"
